FROM alpine:latest

# install packages
RUN apk add --no-cache \
    xvfb \
    x11vnc \
    xterm \
    python3 \
    py3-pip \
    xdotool \
    tzdata \
    fluxbox

RUN ln -fs /usr/share/zoneinfo/UTC /etc/localtime && \
    echo "UTC" > /etc/timezone

# vnc port
EXPOSE 5900

#RUN mkdir /app
WORKDIR /app
COPY . /app

RUN chmod +x /app/start.sh

# Change ownership of /app to the non-root user
#RUN adduser -D -u 1000 appuser
#RUN chown -R appuser:appuser /app
#USER appuser

# start Xxfb, xfce4, and x11vnc
CMD ["/app/start.sh"]