FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive

# install packages
RUN apt-get update && apt-get install -y \
    xvfb \
    x11vnc \
    xfce4 \
    xfce4-goodies \
    dbus-x11 \
    python3 \
    python3-pip \
    xdotool \
    && rm -rf /var/lib/apt/lists/*

RUN ln -fs /usr/share/zoneinfo/UTC /etc/localtime && \
dpkg-reconfigure --frontend noninteractive tzdata

# vnc port
EXPOSE 5900

RUN mkdir /app
WORKDIR /app
COPY . /app

RUN chmod +x /app/start.sh

# start Xxfb, xfce4, and x11vnc
CMD ["/app/start.sh"]